import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'grid',
    gap: '2rem',
    gridTemplateColumns: '380px 1fr',
  },
  panel: {
    background: 'var(--color-surface, #141416)',
    borderRadius: '16px',
    padding: '2rem',
    height: 'fit-content',
    border: '1px solid var(--color-border, #2a2a2e)',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
    paddingBottom: '1.5rem',
    borderBottom: '1px solid var(--color-border, #2a2a2e)',
  },
  heading: {
    fontFamily: 'var(--font-display, "Playfair Display", Georgia, serif)',
    fontSize: '1.5rem',
    fontWeight: 600,
    letterSpacing: '-0.02em',
    margin: 0,
    color: 'var(--color-text, #faf9f7)',
  },
  logoutButton: {
    padding: '0.5rem 1rem',
    background: 'transparent',
    border: '1px solid var(--color-border-accent, #3a3a40)',
    borderRadius: '6px',
    color: 'var(--color-text-muted, #b8b5b0)',
    cursor: 'pointer',
    fontSize: '0.75rem',
    fontWeight: 500,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    transition: 'all 0.2s ease',
  },
  field: {
    marginBottom: '1.5rem',
  },
  label: {
    display: 'block',
    marginBottom: '0.75rem',
    color: 'var(--color-text-muted, #b8b5b0)',
    fontSize: '0.75rem',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.12em',
  },
  input: {
    width: '100%',
    padding: '1rem',
    background: 'var(--color-bg, #0a0a0b)',
    border: '1px solid var(--color-border, #2a2a2e)',
    borderRadius: '8px',
    color: 'var(--color-text, #faf9f7)',
    fontSize: '1rem',
    transition: 'border-color 0.2s ease',
  },
  hint: {
    display: 'block',
    marginTop: '0.5rem',
    fontSize: '0.75rem',
    color: 'var(--color-text-muted, #b8b5b0)',
  },
  button: {
    padding: '1rem 1.25rem',
    background: 'var(--color-surface-elevated, #1a1a1d)',
    border: 'none',
    borderRadius: '8px',
    color: 'var(--color-text, #faf9f7)',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: 600,
    transition: 'all 0.2s ease',
  },
  generateButton: {
    background: 'var(--color-primary, #e63946)',
    width: '100%',
    padding: '1.25rem',
    fontSize: '1rem',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    boxShadow: '0 4px 20px rgba(230, 57, 70, 0.3)',
  },
  buttonContent: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
  },
  spinner: {
    width: '18px',
    height: '18px',
    border: '2px solid rgba(255,255,255,0.3)',
    borderTopColor: '#fff',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  actionSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
  },
  regenerateRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.75rem',
  },
  secondaryButton: {
    background: 'var(--color-surface-accent, #222226)',
    fontSize: '0.875rem',
    padding: '1rem',
  },
  publishButton: {
    background: 'var(--color-success, #4ade80)',
    color: '#000',
    width: '100%',
    padding: '1.25rem',
    fontSize: '1rem',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    boxShadow: '0 4px 20px rgba(74, 222, 128, 0.3)',
  },
  successBox: {
    textAlign: 'center' as const,
    padding: '3rem 1.5rem',
    background: 'var(--color-success-muted, rgba(74, 222, 128, 0.12))',
    borderRadius: '12px',
    border: '1px solid rgba(74, 222, 128, 0.3)',
  },
  successIcon: {
    color: 'var(--color-success, #4ade80)',
    marginBottom: '1.5rem',
    display: 'flex',
    justifyContent: 'center',
  },
  successTitle: {
    fontFamily: 'var(--font-display, "Playfair Display", Georgia, serif)',
    fontSize: '1.5rem',
    fontWeight: 600,
    marginBottom: '0.75rem',
    color: 'var(--color-text, #faf9f7)',
  },
  successPath: {
    color: 'var(--color-text-muted, #b8b5b0)',
    fontSize: '0.875rem',
    fontFamily: 'var(--font-mono, "JetBrains Mono", monospace)',
    marginBottom: '2rem',
    wordBreak: 'break-all' as const,
  },
  newButton: {
    padding: '1rem 2rem',
    background: 'var(--color-primary, #e63946)',
    border: 'none',
    borderRadius: '8px',
    color: '#fff',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: 600,
    boxShadow: '0 4px 20px rgba(230, 57, 70, 0.3)',
  },
  error: {
    marginTop: '1.5rem',
    padding: '1rem',
    background: 'var(--color-error-muted, rgba(248, 113, 113, 0.12))',
    border: '1px solid rgba(248, 113, 113, 0.3)',
    borderRadius: '8px',
    color: 'var(--color-error, #f87171)',
    fontSize: '0.9rem',
  },
  previewArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1.5rem',
  },
  preview: {
    background: 'var(--color-surface, #141416)',
    borderRadius: '16px',
    overflow: 'hidden',
    border: '1px solid var(--color-border, #2a2a2e)',
  },
  publishedPreview: {
    borderColor: 'var(--color-success, #4ade80)',
    boxShadow: '0 0 24px rgba(74, 222, 128, 0.15)',
  },
  previewHeader: {
    padding: '1.25rem 1.5rem',
    borderBottom: '1px solid var(--color-border, #2a2a2e)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: 'var(--color-surface-elevated, #1a1a1d)',
  },
  previewTitle: {
    fontSize: '0.875rem',
    fontWeight: 600,
    margin: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    color: 'var(--color-text, #faf9f7)',
  },
  publishedBadge: {
    background: 'var(--color-success, #4ade80)',
    color: '#000',
    padding: '0.25rem 0.625rem',
    borderRadius: '9999px',
    fontSize: '0.65rem',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  filepath: {
    color: 'var(--color-text-muted, #b8b5b0)',
    fontSize: '0.75rem',
    fontFamily: 'var(--font-mono, "JetBrains Mono", monospace)',
  },
  frontmatter: {
    padding: '1.25rem 1.5rem',
    borderBottom: '1px solid var(--color-border, #2a2a2e)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
  },
  frontmatterRow: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.25rem',
  },
  frontmatterLabel: {
    fontSize: '0.7rem',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.1em',
    color: 'var(--color-text-muted, #b8b5b0)',
  },
  frontmatterValue: {
    fontSize: '0.9rem',
    color: 'var(--color-text-accent, #e8e6e1)',
  },
  content: {
    padding: '1.5rem',
    maxHeight: '450px',
    overflow: 'auto',
    background: 'var(--color-bg, #0a0a0b)',
  },
  markdown: {
    fontFamily: 'var(--font-mono, "JetBrains Mono", monospace)',
    fontSize: '0.85rem',
    whiteSpace: 'pre-wrap' as const,
    margin: 0,
    color: 'var(--color-text-accent, #e8e6e1)',
    lineHeight: 1.7,
  },
  imagePreview: {
    padding: '1.5rem',
    textAlign: 'center' as const,
    background: 'var(--color-bg, #0a0a0b)',
  },
  image: {
    maxWidth: '100%',
    maxHeight: '350px',
    borderRadius: '8px',
    boxShadow: '0 12px 24px -4px rgba(0, 0, 0, 0.5)',
  },
  imageAlt: {
    marginTop: '0.75rem',
    color: 'var(--color-text-muted, #b8b5b0)',
    fontSize: '0.875rem',
    fontStyle: 'italic' as const,
  },
  // Tab Navigation
  tabNav: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1.5rem',
    padding: '0.25rem',
    background: 'var(--color-bg, #0a0a0b)',
    borderRadius: '8px',
  },
  tab: {
    flex: 1,
    padding: '0.75rem 1rem',
    background: 'transparent',
    border: 'none',
    borderRadius: '6px',
    color: 'var(--color-text-muted, #9a9590)',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontWeight: 500,
    transition: 'all 0.2s ease',
  },
  tabActive: {
    background: 'var(--color-surface-elevated, #1a1a1d)',
    color: 'var(--color-text, #faf9f7)',
  },
  // Settings Tab
  panelFullWidth: {
    maxWidth: '100%',
  },
  settingsContent: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1.5rem',
  },
  subTabNav: {
    display: 'flex',
    gap: '0.375rem',
    flexWrap: 'wrap' as const,
  },
  subTab: {
    padding: '0.5rem 1rem',
    background: 'transparent',
    border: '1px solid var(--color-border, #2a2a2e)',
    borderRadius: '9999px',
    color: 'var(--color-text-muted, #9a9590)',
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 500,
    transition: 'all 0.2s ease',
    whiteSpace: 'nowrap' as const,
  },
  subTabActive: {
    background: 'var(--color-surface-elevated, #1a1a1d)',
    color: 'var(--color-text, #faf9f7)',
    borderColor: 'var(--color-border-accent, #3a3a40)',
  },
  cardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))',
    gap: '1rem',
  },
  settingsCard: {
    background: 'var(--color-bg, #0a0a0b)',
    borderRadius: '12px',
    padding: '1.25rem',
    border: '1px solid var(--color-border, #2a2a2e)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
  },
  settingsCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  settingsItemLabel: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'var(--color-text, #faf9f7)',
  },
  settingsItemCategory: {
    fontSize: '0.65rem',
    fontWeight: 500,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    padding: '0.25rem 0.5rem',
    background: 'var(--color-surface-elevated, #1a1a1d)',
    borderRadius: '4px',
    color: 'var(--color-text-muted, #9a9590)',
  },
  settingsItemValue: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
  },
  cardPreview: {
    fontSize: '0.8rem',
    fontFamily: 'var(--font-mono, "JetBrains Mono", monospace)',
    color: 'var(--color-text-muted, #9a9590)',
    margin: 0,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    lineHeight: 1.5,
    maxHeight: '200px',
    overflow: 'auto',
  },
  editArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
  },
  textarea: {
    width: '100%',
    padding: '0.75rem',
    background: 'var(--color-surface, #141416)',
    border: '1px solid var(--color-border-accent, #3a3a40)',
    borderRadius: '6px',
    color: 'var(--color-text, #faf9f7)',
    fontSize: '0.85rem',
    fontFamily: 'var(--font-mono, "JetBrains Mono", monospace)',
    resize: 'vertical' as const,
    lineHeight: 1.5,
  },
  editButtons: {
    display: 'flex',
    gap: '0.5rem',
    justifyContent: 'flex-end',
  },
  smallButton: {
    padding: '0.5rem 1rem',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.75rem',
    fontWeight: 600,
    transition: 'all 0.2s ease',
  },
  editButton: {
    background: 'var(--color-surface-elevated, #1a1a1d)',
    color: 'var(--color-text, #faf9f7)',
    alignSelf: 'flex-start',
  },
  saveButton: {
    background: 'var(--color-primary, #e63946)',
    color: '#fff',
  },
  cancelButton: {
    background: 'transparent',
    border: '1px solid var(--color-border, #2a2a2e)',
    color: 'var(--color-text-muted, #9a9590)',
  },
  loadingBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    padding: '2rem',
    color: 'var(--color-text-muted, #9a9590)',
  },
  // Planner styles
  plannerContent: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1.5rem',
  },
  plannerForm: {
    background: 'var(--color-bg, #0a0a0b)',
    borderRadius: '12px',
    padding: '1.25rem',
    border: '1px solid var(--color-border, #2a2a2e)',
  },
  plannerFormRow: {
    display: 'flex',
    gap: '1rem',
    alignItems: 'flex-end',
  },
  plannerList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
  },
  plannerCard: {
    background: 'var(--color-bg, #0a0a0b)',
    borderRadius: '12px',
    border: '1px solid var(--color-border, #2a2a2e)',
    overflow: 'hidden',
  },
  plannerCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 1.25rem',
    borderBottom: '1px solid var(--color-border, #2a2a2e)',
    background: 'var(--color-surface-elevated, #1a1a1d)',
    flexWrap: 'wrap' as const,
    gap: '0.75rem',
  },
  plannerCardMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  plannerDate: {
    fontSize: '0.9rem',
    fontWeight: 600,
    color: 'var(--color-text, #faf9f7)',
    fontFamily: 'var(--font-mono, "JetBrains Mono", monospace)',
  },
  statusBadge: {
    padding: '0.2rem 0.5rem',
    borderRadius: '9999px',
    fontSize: '0.65rem',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    border: '1px solid',
  },
  plannerInputType: {
    fontSize: '0.65rem',
    fontWeight: 500,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    padding: '0.2rem 0.5rem',
    background: 'var(--color-surface, #141416)',
    borderRadius: '4px',
    color: 'var(--color-text-muted, #9a9590)',
  },
  plannerCardActions: {
    display: 'flex',
    gap: '0.5rem',
    flexWrap: 'wrap' as const,
  },
  plannerCardBody: {
    padding: '1rem 1.25rem',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
  },
  plannerInput: {
    fontSize: '0.9rem',
    color: 'var(--color-text-accent, #e8e6e1)',
    wordBreak: 'break-all' as const,
  },
  plannerImagePreview: {
    borderRadius: '8px',
    overflow: 'hidden',
    background: 'var(--color-bg, #0a0a0b)',
    textAlign: 'center' as const,
  },
  plannerImage: {
    maxWidth: '100%',
    maxHeight: '250px',
    borderRadius: '8px',
    objectFit: 'cover' as const,
  },
  plannerPreview: {
    padding: '0.75rem',
    background: 'var(--color-surface, #141416)',
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.5rem',
  },
  plannerPublishedPath: {
    fontSize: '0.75rem',
    fontFamily: 'var(--font-mono, "JetBrains Mono", monospace)',
    color: 'var(--color-success, #4ade80)',
    padding: '0.5rem 0.75rem',
    background: 'rgba(74, 222, 128, 0.08)',
    borderRadius: '6px',
  },
  previewLink: {
    background: 'var(--color-surface-accent, #222226)',
    color: 'var(--color-text, #faf9f7)',
  },
  srOnly: {
    position: 'absolute' as const,
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap' as const,
    borderWidth: 0,
  },
  emptyState: {
    textAlign: 'center' as const,
    padding: '3rem 1.5rem',
    color: 'var(--color-text-muted, #9a9590)',
    fontSize: '0.9rem',
    background: 'var(--color-bg, #0a0a0b)',
    borderRadius: '12px',
    border: '1px dashed var(--color-border, #2a2a2e)',
  },
};
